### ISSUE TITLE
Feat: 支持带密码的密钥

### ISSUE THREAD

**Issue by SummonHIM** [TransparentLC/LiteLoaderQQNT-PGP-Encryption#1]
```
Uncaught Error: Error invoking remote method 'PGP_Encryption.encryptMessage': Error: Error encrypting message: Signing key is not decrypted.
```
能否支持一下带密码的密钥。谢谢大佬。

还有个小想法是。直接接入gpg-agent？通过现有的密钥环境签名这样子？毕竟有原生的密码输入。

**Comment by SummonHIM** [comment]
漏看局限性了

**Comment by TransparentLC** [comment]
gpg-agent 这个还真的可以加，这样带密码的密钥和硬件密钥好像都能支持了？

但是我对这东西完全不熟，那就只能等哪位愿意自己动手然后 PR 了。

> 通过现有的密钥环境

签名的时候不使用 OpenPGP.js 而是直接用 `child_process` 调用 `gpg` 是不是也可以啊（笑

**Comment by SummonHIM** [comment]
> 签名的时候不使用 OpenPGP.js 而是直接用 `child_process` 调用 `gpg` 是不是也可以啊（笑

对，git其实也是直接执行gpg代码获取的

**Comment by SummonHIM** [comment]
https://github.com/git-for-windows/git/blob/main/gpg-interface.c

**Comment by TransparentLC** [comment]
* `gpg --encrypt --armor --sign --recipient <KeyID> --local-user <KeyID>`
* `gpg --decrypt`

打算加个开关，暂时定为“使用系统安装的 GnuPG 进行加密和解密”。加密仍然需要在插件中选择私钥和绑定公钥，找到两个 KeyID 然后 `child_process` 调用 `gpg` 加密；解密的话，GnuPG 的钥匙串里有私钥就可以解密，不需要导入插件。

**Comment by SummonHIM** [comment]
这样子不错 顺便加个指定gpg位置的text选项？

**Comment by TransparentLC** [comment]
这个需要额外指定吗？会有把 `gpg` 放在 PATH 以外的目录的情况吗？

**Comment by SummonHIM** [comment]
谁知道呢，每个人安装gpg方式千奇百怪🤣

**Comment by TransparentLC** [comment]
在最新的 commit 里已经加上这个功能了，试一下有没有什么问题？

> 这样子不错 顺便加个指定gpg位置的text选项？

想了想，还是不打算加。

**Comment by SummonHIM** [comment]
似乎刷新密钥有些频繁了？我每次进入设置都要输入一遍密码。只要点取消，个人密钥就失效了。输入密码之后也是显示undefined。

edit: 公钥绑定没事 我忘记点保存了

**Comment by SummonHIM** [comment]
自动解密也没有了

我用kleopatra加密的消息能够自动解密。用ctrl+/的不行。而且只能对方看到。我自己是解不出的。

懂了 加密密钥只用了对面的公钥 没用我的密钥

**Comment by TransparentLC** [comment]
> 加密密钥只用了对面的公钥 没用我的密钥

我弄错了，应该写两个 `--recipient` 把对方和自己的 KeyID 都写上，已经加上了

**Comment by TransparentLC** [comment]
> 我每次进入设置都要输入一遍密码

因为每次打开设置会读取一遍密钥，`gpg --armor --export-secret-keys` 碰到带密码的密钥就会弹框要求输入密码，不输密码就导出不了。

undefined 这个我再想想怎么办……

**Comment by SummonHIM** [comment]
> > 我每次进入设置都要输入一遍密码
> 
> 因为每次打开设置会读取一遍密钥，`gpg --armor --export-secret-keys` 碰到带密码的密钥就会弹框要求输入密码，不输密码就导出不了。
> 
> undefined 这个我再想想怎么办……

或者直接用gpg --list-secret-keys --with-colons来获取id？这样还能避免导出完整的密钥信息。毕竟都通过系统来签名加密了

**Comment by TransparentLC** [comment]
有道理，毕竟插件只需要 KeyID、UserID 和算法信息，不需要密钥的具体内容。

需要解析这个输出，我先把相关的东西记在这里：

* https://github.com/gpg/gnupg/blob/master/doc/DETAILS
* https://github.com/unusualbob/gpgKeylistParser

**Comment by SummonHIM** [comment]
这个选择的undefind似乎是那个监听有问题
![image](https://github.com/user-attachments/assets/5c1d004c-c18a-4586-8761-75a6b133b695)

**Comment by TransparentLC** [comment]
LiteLoader 自带的这些组件不能像 HTML 标准组件一样用 v-model，用起来非常难受，写设置界面的时候费了很大的劲……

关于那个 PR 的修改，应该不会有第三种能用的 GPG 实现了，那改成 select 是否还有必要？以及集成 GnuPG 之后我在考虑要不要把 OpenPGP.js 去掉，毕竟同时维护两个的话还是有点麻烦的。

然后那个是否是 PGP 消息的检测，换行不是多余的，而且 BEGIN 后面应该有两个换行，用 Kleopatra 试了一下 `-----BEGIN PGP MESSAGE-----` 和 Base64 之间小于两个换行或者 `-----END PGP MESSAGE-----` 和最后的 checksum 之间没有换行会无法解密。

**Comment by SummonHIM** [comment]
> LiteLoader 自带的这些组件不能像 HTML 标准组件一样用 v-model，用起来非常难受，写设置界面的时候费了很大的劲……
> 
> 关于那个 PR 的修改，应该不会有第三种能用的 GPG 实现了，那改成 select 是否还有必要？以及集成 GnuPG 之后我在考虑要不要把 OpenPGP.js 去掉，毕竟同时维护两个的话还是有点麻烦的。
> 
> 然后那个是否是 PGP 消息的检测，换行不是多余的，而且 BEGIN 后面应该有两个换行，用 Kleopatra 试了一下 `-----BEGIN PGP MESSAGE-----` 和 Base64 之间小于两个换行或者 `-----END PGP MESSAGE-----` 和最后的 checksum 之间没有换行会无法解密。

那个在系统gpg模式下 总是无法解密，删掉就能100%解密

**Comment by SummonHIM** [comment]
> 关于那个 PR 的修改，应该不会有第三种能用的 GPG 实现了，那改成 select 是否还有必要？以及集成 GnuPG 之后我在考虑要不要把 OpenPGP.js 去掉，毕竟同时维护两个的话还是有点麻烦的。

那干脆直接就去掉OpenPGP.js？

**Comment by TransparentLC** [comment]
> 那个在系统gpg模式下 总是无法解密，删掉就能100%解密

我这里没碰到这个问题，可以 F12 看一下从界面上获取到的消息是什么样的。

https://github.com/TransparentLC/LiteLoaderQQNT-PGP-Encryption/blob/752ff7d3565f377163fc6da31f3701c8a19ebc44/src/renderer/index.ts#L155-L156
https://github.com/TransparentLC/LiteLoaderQQNT-PGP-Encryption/blob/752ff7d3565f377163fc6da31f3701c8a19ebc44/src/renderer/index.ts#L172

![](https://github.com/user-attachments/assets/4f5ff7ae-b1f7-410e-807b-afd1773695f8)

> 那干脆直接就去掉OpenPGP.js？

那就确定了。

**Comment by SummonHIM** [comment]
> > 那个在系统gpg模式下 总是无法解密，删掉就能100%解密
> 
> 我这里没碰到这个问题，可以 F12 看一下从界面上获取到的消息是什么样的。
> 
> https://github.com/TransparentLC/LiteLoaderQQNT-PGP-Encryption/blob/752ff7d3565f377163fc6da31f3701c8a19ebc44/src/renderer/index.ts#L155-L156
> 
> 
> https://github.com/TransparentLC/LiteLoaderQQNT-PGP-Encryption/blob/752ff7d3565f377163fc6da31f3701c8a19ebc44/src/renderer/index.ts#L172
> 
> ![](https://private-user-images.githubusercontent.com/47057319/394217622-4f5ff7ae-b1f7-410e-807b-afd1773695f8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM4MjQ1MTAsIm5iZiI6MTczMzgyNDIxMCwicGF0aCI6Ii80NzA1NzMxOS8zOTQyMTc2MjItNGY1ZmY3YWUtYjFmNy00MTBlLTgwN2ItYWZkMTc3MzY5NWY4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjEwVDA5NTAxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVmZDA3ZjA3OWE0NmJjNDQ3NjkyMGYxMjY2MjU0ZmU5OGE3Y2MxZDhlMmQ5MmQ5ZDE5NmMyYTdiYjU2MTdjODYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.L8idEgpbIoGD5jos2ihHptub7oWVRPsb0SIlOOMDI5k)
> 
> > 那干脆直接就去掉OpenPGP.js？
> 
> 那就确定了。

我试过了 他压根就没这条日志

**Comment by SummonHIM** [comment]
是否是我这个pgp，换行是crlf?

**Comment by TransparentLC** [comment]
![](https://github.com/user-attachments/assets/1bf97a9b-c04a-4cfd-8c36-0717b1035ed2)

看样子是没有 \r 的

**Comment by SummonHIM** [comment]
我靠 我知道了 -----BEGIN PGP MESSAGE----- \n有个空格。要不用regex?
![image](https://github.com/user-attachments/assets/c12392c3-88c6-4154-ba8f-4a693738a4ab)

**Comment by TransparentLC** [comment]
还真是，BEGIN 之后 END 之前加空格也可以，但是换行还是必须要有

**Comment by SummonHIM** [comment]
```
-----BEGIN PGP MESSAGE-----\s*?\n([\s\S]*)-----END PGP MESSAGE-----
```
![image](https://github.com/user-attachments/assets/be1e20d0-d050-412f-8e28-d2810999342f)

**Comment by TransparentLC** [comment]
`^-----BEGIN PGP MESSAGE-----\s*(?:.+?:.*\n)*\s*\n(?:[A-Za-z\d+/]*\n?)*={0,2}\n=(?:[A-Za-z\d+/]{4})?\n\s*-----END PGP MESSAGE-----\s*$`

修改自 https://regex101.com/library/90b6kK

可以去 [Regex Vis](https://regex-vis.com/?r=%5E-----BEGIN+PGP+MESSAGE-----%5Cs*%28%3F%3A.%2B%3F%3A.*%5Cn%29*%5Cs*%5Cn%28%3F%3A%5BA-Za-z%5Cd%2B%2F%5D*%5Cn%3F%29*%3D%7B0%2C2%7D%5Cn%3D%28%3F%3A%5BA-Za-z%5Cd%2B%2F%5D%7B4%7D%29%3F%5Cn%5Cs*-----END+PGP+MESSAGE-----%5Cs*%24) 上测试

**Comment by SummonHIM** [comment]
第一次见节点式的regex调试器

**Comment by TransparentLC** [comment]
上面的正则表达式不能用，可能会出现无限递归的问题，导致出现这条消息的窗口卡死。

```js
// 每一行后面有一个空格
`-----BEGIN PGP MESSAGE----- 

xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx 
xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx 
xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx 
xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx 
xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx 
xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx 
xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx 
=xxxx 
-----END PGP MESSAGE----- `.match(/^-----BEGIN PGP MESSAGE-----\s*(?:.+?:.*\n)*\s*\n(?:[A-Za-z\d+\/]*\n?)*={0,2}\n=(?:[A-Za-z\d+\/]{4})?\n\s*-----END PGP MESSAGE-----\s*$/);
```

**Comment by TransparentLC** [comment]
用 GnuPG 替换 OpenPGP.js 已经完成了，带密码的私钥应该是能用的，可以再试一下有没有什么问题。

**Comment by SummonHIM** [comment]
单人测试完全ok，没有问题
请问下 群聊加密要怎么设置？

**Comment by TransparentLC** [comment]
目前想到的是两种做法：

1. 单独准备一个群聊专用的密钥，将私钥发给其他群友，用这一个公钥来加密
2. 收集所有群友的公钥，用它们来加密（使用 PGP 可以做到，但是还不能使用插件进行这样的加密，因为目前一个 QQ 号/群号只能对应一个公钥，另外加密的时候可以解密的人就固定了，之后有新的群友的话也不能解密这条消息）

**Comment by SummonHIM** [comment]
多谢！

**Comment by SummonHIM** [comment]
顺便贴一下这个链接在Readme里？
https://wiki.archlinux.org/title/GnuPG#Disable_unsupported_AEAD_mechanism
![image](https://github.com/user-attachments/assets/d70ac6df-67cb-4a32-8def-010564844730)
不禁用AEAD，没办法在某些gpg里解密

**Comment by TransparentLC** [comment]
已添加

**Comment by TransparentLC** [comment]
> 收集所有群友的公钥，用它们来加密（使用 PGP 可以做到，但是还不能使用插件进行这样的加密，因为目前一个 QQ 号/群号只能对应一个公钥，另外加密的时候可以解密的人就固定了，之后有新的群友的话也不能解密这条消息）

在 v0.2.1 中已经添加了

**Comment by SummonHIM** [comment]
群聊测试正常

**Comment by SummonHIM** [comment]
OpenKeychain生成的密钥 没法被Regex捕获到

**Comment by TransparentLC** [comment]
插件只会识别加密消息，不会识别密钥

**Comment by SummonHIM** [comment]
> 插件只会识别加密消息，不会识别密钥

打错了
是生成的消息

**Comment by SummonHIM** [comment]
我再找找有没有相关的

**Comment by SummonHIM** [comment]
懂了 END后面 他后面多了个\n

**Comment by SummonHIM** [comment]
```
^-----BEGIN PGP MESSAGE-----\s*?\n
```
![image](https://github.com/user-attachments/assets/5c1feafc-e841-4712-9736-72df5df0a8d6)

```
-----END PGP MESSAGE-----[\s|\n]*?$
```
![image](https://github.com/user-attachments/assets/f6addfd6-ab6d-42b7-9305-26f0619be648)

**Comment by TransparentLC** [comment]
`-----END PGP MESSAGE-----\s*$` 就可以了，`\s` 已经包括换行符了，而且 `[]` 里面不需要写 `|`。

**Comment by SummonHIM** [comment]
> `-----END PGP MESSAGE-----\s*$` 就可以了，`\s` 已经包括换行符了，而且 `[]` 里面不需要写 `|`。

加上问号？允许没有空格的情况。`-----END PGP MESSAGE-----\s*?$`

**Comment by TransparentLC** [comment]
`*` 就已经是表示匹配零次或更多次了
